# Generated by Django 4.2.14 on 2024-07-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url_title',
            field=models.CharField(max_length=128, verbose_name='عنوان لینک'),
        ),
    ]
