# Generated by Django 4.2.14 on 2024-07-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_slider_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='sec_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان فرعی'),
        ),
    ]
