# Generated by Django 4.2.11 on 2024-04-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productbrand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='product_categories', to='product.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
