# Generated by Django 4.2.14 on 2024-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='GNgeexlWJnCJETjI7S0lhqK11TYzJZ0ZgmTVZ9KUliu7RoPGDHxjC9N3AcCXIHiAIIN6J0E5H05a6zSsHvnnZPr0cKsQB8aWM2q9eaFwwmQs2EPkaZdjeO4S8Jy2wWU5', max_length=128),
        ),
    ]
