# Generated by Django 4.2.14 on 2024-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='7g2abcFRTzLNGsYVpVc2SvbOEHwFSnD20thQa5v4QcFhPlGhzQIpnYHtkTerDTmA2PVem2Q4obd8Aa0yozzNhzHHC6sVhzZmeqr3mlDylHovShWKLeEJs2IBgPal0qvn', max_length=128),
        ),
    ]
