# Generated by Django 4.2.14 on 2024-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(db_index=True, default='6eWL81RGOmGCT5VxUjytMLlMengkFfqOc2e3u9gnVLXdKXmdhV9mZu004KbaBBFgqJlb85az8TuD55tI6FBXR3jCPJdy5Tj8KOTyEojDVhBfFGNsa9FStYogoEepWChl', editable=False, max_length=128),
        ),
    ]
