# Generated by Django 4.2.14 on 2024-07-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(db_index=True, default='SZtVDWNWYTSsGOBQcSE083WBbyt9HfDtt9uWMOcNmi3bhGQMhxLJreCDws2YfUbUd98rvjlxfGp2wvGXB57S9v8KUhXQQFsXZv6WaiO8bDnFRrWTitV18SDexFyNLlID', editable=False, max_length=128),
        ),
    ]
