# Generated by Django 4.2.14 on 2024-07-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(db_index=True, default='lYx2tSmzoxukSW6GM3JvXaXx39l7SWpSPw3pGxCK5TSPs7UZyjinlEQBIuTtSMPTHOD82jKM4CQYzbYGvcU4jjpJdEDCV0oB4OtCrNKlaPSoDBUUH2AqM3MYohjdXmyZ', editable=False, max_length=128),
        ),
    ]
