# Generated by Django 4.2.14 on 2024-07-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(db_index=True, default='RYy3CVDhNUJjQx2AWsWWx147U6LTPPjgc77XIlYGgKmaduuLat7E3S7DAhsF7xEq3hGJmgUH9xyFPSgbSu2odVDEBVOYoroc0hrqn0nuaZR73yUR2B7CVuT2vp1Y7Uv7', editable=False, max_length=128),
        ),
    ]
