# Generated by Django 4.2.14 on 2024-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(db_index=True, default='8JWRdBkBiJxDEmvSIvuys1HTHqd207fT2wijiYPy1F34DyUeVWEwFD4wRYtbInUAcYfk0Le4AMS4g1J8SRuXV6vOjdNwK5ME0aHo9wvELmwaeaUyvhlVphMS5QBBupma', editable=False, max_length=128),
        ),
    ]
