# Generated by Django 4.2.14 on 2024-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Images/user/avatar', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(db_index=True, default='YMXgNnpcGfjA147RVRKxcu4V3d8xNytMRJbFTAg1mDVkSTEoROSD8EZxsqwklFNMU2xT1uUDQoUL5yNpyX6uVeIG0yMRUT2k1prSgIh7ZnexKhgRLEQadAe9F0mVRzGt', editable=False, max_length=128, verbose_name='Verification Code'),
        ),
    ]
