# Generated by Django 4.2.14 on 2024-07-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_about_user_address_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(db_index=True, default='kYaGl4dmXwAGDMB5IEdRS3YVW3hZ8dU0pYPageB5ot9TxQaPxfazYYc7sXb9r42EYI7bUJV3FOo0WhgFpn45shbHX9vPJ8ExfvazVDCfZfGHqOkhTXQZlrdHjlCcVLjW', editable=False, max_length=128, verbose_name='Verification Code'),
        ),
    ]
