# Generated by Django 4.2.14 on 2024-07-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس')),
                ('fax', models.CharField(blank=True, max_length=128, null=True, verbose_name='فکس')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='ایمیل')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما سایت')),
                ('is_main_setting', models.BooleanField(default=False, verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'مشخصات درباره ما',
            },
        ),
    ]
