# Generated by Django 4.2.14 on 2024-07-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
